apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    subject: custom_litmus
  name: test-workflow-push-3
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: ecs-agent-stop-4iv
        template: ecs-agent-stop-4iv
      - arguments: {}
        name: azure-instance-stop-6k3
        template: azure-instance-stop-6k3
  - container:
      args:
      - kubectl apply -f /tmp/ecs-agent-stop-4iv.yaml -n {{workflow.parameters.adminModeNamespace}}
        | kubectl apply -f /tmp/azure-instance-stop-6k3.yaml -n {{workflow.parameters.adminModeNamespace}}
        |  sleep 30
      command:
      - sh
      - -c
      image: chaosnative/k8s:2.11.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: ecs-agent-stop-4iv
        path: /tmp/ecs-agent-stop-4iv.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: >
                It stops the ECS agent container in all the container Instances of ECS
                Cluster
            kind: ChaosExperiment
            metadata:
              name: ecs-agent-stop
              labels:
                name: ecs-agent-stop
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: latest
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: chaosnative/go-runner:ci
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name ecs-agent-stop
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "30"
                  - name: RAMP_TIME
                    value: ""
                  - name: CHAOS_INTERVAL
                    value: "10"
                  - name: LIB
                    value: litmus
                  - name: DOCUMENT_PATH
                    value: Litmus-AWS-SSM-Docs-For-Agent-Stop.yml
                  - name: DOCUMENT_NAME
                    value: Litmus-AWS-SSM-Docs-For-Agent-Stop
                  - name: DOCUMENT_FORMAT
                    value: YAML
                  - name: DOCUMENT_TYPE
                    value: Command
                  - name: AWS_SHARED_CREDENTIALS_FILE
                    value: /tmp/cloud_config.yml
                labels:
                  name: ecs-agent-stop
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: latest
                secrets:
                  - name: cloud-secret
                    mountPath: /tmp/
      - name: azure-instance-stop-6k3
        path: /tmp/azure-instance-stop-6k3.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Stops an azure instance for a certain chaos duration
            kind: ChaosExperiment
            metadata:
              name: azure-instance-stop
              labels:
                name: azure-instance-stop
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: latest
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - secrets
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: chaosnative/go-runner:ci
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name azure-instance-stop
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "30"
                  - name: CHAOS_INTERVAL
                    value: "30"
                  - name: RAMP_TIME
                    value: ""
                  - name: AZURE_INSTANCE_NAME
                    value: ""
                  - name: RESOURCE_GROUP
                    value: ""
                  - name: SCALE_SET
                    value: ""
                  - name: AZURE_AUTH_LOCATION
                    value: /tmp/azure.auth
                  - name: SEQUENCE
                    value: parallel
                  - name: LIB
                    value: litmus
                labels:
                  name: azure-instance-stop
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: latest
                secrets:
                  - name: cloud-secret
                    mountPath: /tmp/
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-ecs-agent-stop-4iv.yaml
      - -saveName=/tmp/engine-name
      image: chaosnative/litmus-checker:2.11.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: ecs-agent-stop-4iv
        path: /tmp/chaosengine-ecs-agent-stop-4iv.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: ecs-agent-stop-4iv
              labels:
                instance_id: f96c9465-3746-4c11-bdaf-f3b7d309b455
                workflow_name: custom-1659945929
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: ecs-agent-stop
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "10"
                        - name: CLUSTER_NAME
                          value: ""
                        - name: REGION
                          value: ""
                        - name: SEQUENCE
                          value: parallel
    metadata:
      labels:
        weight: "10"
    name: ecs-agent-stop-4iv
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-azure-instance-stop-6k3.yaml
      - -saveName=/tmp/engine-name
      image: chaosnative/litmus-checker:2.11.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: azure-instance-stop-6k3
        path: /tmp/chaosengine-azure-instance-stop-6k3.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: azure-instance-stop-6k3
              labels:
                instance_id: 436a3ef5-925f
                workflow_name: custom-1659945929
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: azure-instance-stop
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "30"
                        - name: AZURE_INSTANCE_NAME
                          value: ""
                        - name: RESOURCE_GROUP
                          value: ""
                        - name: SCALE_SET
                          value: ""
    metadata:
      labels:
        weight: "10"
    name: azure-instance-stop-6k3
    outputs: {}
status:
  finishedAt: null
  startedAt: null
