apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: pod-http-modify-body 
  version: 0.1.0
  annotations:
    categories: kubernetes
spec:
  displayName: pod-http-modify-body 
  categoryDescription: >
    Pod-http-modify-body contains chaos to disrupt http requests of kubernetes pods. This experiment can modify the body of the response from the service targetted. 
    - Causes modification of response body of the HTTP request.
    - The application pod should be healthy once chaos is stopped. Service-requests should be served despite chaos.
  keywords: 
    - kubernetes
  platforms: 
    - "Minikube"
  maintainers: 
    - name: Akash Shrivastava 
      email: akash.shrivastava@harness.io 
  minKubeVersion: 1.12.0 
  provider: 
    name: Harness
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - base64data: ""
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/pod-http-modify-body/experiment.yaml