apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: default
spec:
  # It can be active/stop
  engineState: 'active'
  auxiliaryAppInfo: ''
  chaosServiceAccount: docker-service-kill-sa
  experiments:
    - name: docker-service-kill
      spec:
        components:
        # nodeSelector: 
        #   # provide the node labels
        #   kubernetes.io/hostname: 'node02'
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '90' # in seconds
              
            - name: TARGET_NODE
              value: ''
        probe:
          - name: healthcheck
            type: cmdProbe
            mode: Edge
            runProperties:
              probeTimeout: 180
              retry: 0
              interval: 1
              stopOnFailure: true
            cmdProbe/inputs:
              command: ./healthcheck -name node-level
              source:
                image: chaosnative/go-runner:ci
                inheritInputs: true
              comparator:
                type: string
                criteria: contains
                value: "[P000]"