apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
    subject: custom_litmus
    workflow_id: a3cc3e66-b82b-40e9-a2f3-a6570762e036
    workflows.argoproj.io/controller-instanceid: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
  name: custom-1662068770
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: vmware-dns-chaos-gta
        template: vmware-dns-chaos-gta
  - container:
      args:
      - kubectl apply -f /tmp/vmware-dns-chaos-gta.yaml -n {{workflow.parameters.adminModeNamespace}}
        &&  sleep 30
      command:
      - sh
      - -c
      image: chaosnative/k8s:2.12.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: vmware-dns-chaos-gta
        path: /tmp/vmware-dns-chaos-gta.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: >
                It inject dns error chaos on the provided VMware VMs for a certain chaos
                duration.
            kind: ChaosExperiment
            metadata:
              name: vmware-dns-chaos
              labels:
                name: vmware-dns-chaos
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: latest
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: uditgaurav/go-runner:vmware-dns
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name vmware-dns-chaos
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: RAMP_TIME
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: GOVC_URL
                    valueFrom:
                      secretKeyRef:
                        name: vcenter-secret
                        key: VCENTERSERVER
                  - name: GOVC_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: vcenter-secret
                        key: VCENTERUSER
                  - name: GOVC_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: vcenter-secret
                        key: VCENTERPASS
                  - name: GOVC_INSECURE
                    value: "true"
                  - name: SEQUENCE
                    value: parallel
                labels:
                  name: vmware-dns-chaos
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: latest
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-vmware-dns-chaos-gta.yaml
      - -saveName=/tmp/engine-name
      image: chaosnative/litmus-checker:2.12.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: vmware-dns-chaos-gta
        path: /tmp/chaosengine-vmware-dns-chaos-gta.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: vmware-dns-chaos-gta
              labels:
                workflow_run_id: "{{workflow.uid}}"
                workflow_name: custom-1662068770
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: vmware-dns-chaos
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: VM_NAME
                          value: vm2
                        - name: VM_USER_NAME
                          value: vm2
                        - name: VM_PASSWORD
                          value: "123"
                        - name: TARGET_HOSTNAMES
                          value: google.com
                        - name: MATCH_SCHEME
                          value: substring
                        - name: PORT
                          value: "54"
                        - name: SEQUENCE
                          value: parallel
                    probe: []
    metadata:
      labels:
        weight: "10"
    name: vmware-dns-chaos-gta
    outputs: {}
status:
  finishedAt: null
  startedAt: null
