apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
    subject: custom_litmus
    workflow_id: 6b689c85-7800-4d41-8c80-ce2742657d0a
    workflows.argoproj.io/controller-instanceid: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
  name: custom-1662119912
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: gcp-vm-instance-stop-3pp
        template: gcp-vm-instance-stop-3pp
  - container:
      args:
      - kubectl apply -f /tmp/gcp-vm-instance-stop-3pp.yaml -n {{workflow.parameters.adminModeNamespace}}
        &&  sleep 30
      command:
      - sh
      - -c
      image: sarthak.ai/jain/k8s:2.12.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: gcp-vm-instance-stop-3pp
        path: /tmp/gcp-vm-instance-stop-3pp.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: >
                Stops GCP VM instances and GKE nodes for a specified duration and later
                restarts them
            kind: ChaosExperiment
            metadata:
              name: gcp-vm-instance-stop
              labels:
                name: gcp-vm-instance-stop
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: latest
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - secrets
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                  - apiGroups:
                      - ""
                    resources:
                      - nodes
                    verbs:
                      - get
                      - list
                image: chaosnative/go-runner:ci
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name gcp-vm-instance-stop
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "30"
                  - name: CHAOS_INTERVAL
                    value: "30"
                  - name: SEQUENCE
                    value: parallel
                  - name: LIB
                    value: litmus
                  - name: RAMP_TIME
                    value: ""
                  - name: MANAGED_INSTANCE_GROUP
                    value: disable
                  - name: VM_INSTANCE_NAMES
                    value: ""
                  - name: GCP_PROJECT_ID
                    value: ""
                  - name: INSTANCE_ZONES
                    value: ""
                labels:
                  name: gcp-vm-instance-stop
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: latest
                secrets:
                  - name: cloud-secret
                    mountPath: /tmp/
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-gcp-vm-instance-stop-3pp.yaml
      - -saveName=/tmp/engine-name
      image: sarthak.ai/jain/litmus-checker:2.12.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: gcp-vm-instance-stop-3pp
        path: /tmp/chaosengine-gcp-vm-instance-stop-3pp.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              generateName: gcp-vm-instance-stop-3pp
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              labels:
                workflow_run_id: "{{workflow.uid}}"
                workflow_name: custom-1662119912
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: gcp-vm-instance-stop
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "30"
                        - name: VM_INSTANCE_NAMES
                          value: ""
                        - name: GCP_PROJECT_ID
                          value: ""
                        - name: INSTANCE_ZONES
                          value: ""
                        - name: MANAGED_INSTANCE_GROUP
                          value: disable
                        - name: SEQUENCE
                          value: parallel
    metadata:
      labels:
        weight: "10"
    name: gcp-vm-instance-stop-3pp
    outputs: {}
status:
  finishedAt: null
  startedAt: null
