apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
    subject: custom_litmus
    workflow_id: d32075e0-0b6d-4552-a06c-1a8c0bcb1cbf
    workflows.argoproj.io/controller-instanceid: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
  name: custom-1662133157
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: rds-instance-delete-ztq
        template: rds-instance-delete-ztq
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
  - container:
      args:
      - kubectl apply -f /tmp/rds-instance-delete-ztq.yaml -n {{workflow.parameters.adminModeNamespace}}
        &&  sleep 30
      command:
      - sh
      - -c
      image: chaosnative/k8s:2.12.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: rds-instance-delete-ztq
        path: /tmp/rds-instance-delete-ztq.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                It injects rds-instance-delete chaos on RDS cluster
            kind: ChaosExperiment
            metadata:
              name: rds-instance-delete
              labels:
                name: rds-instance-delete
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: latest
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: chaosnative/go-runner:ci
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name rds-instance-delete
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "30"
                  - name: RAMP_TIME
                    value: ""
                  - name: CHAOS_INTERVAL
                    value: "10"
                  - name: STATUS_CHECK_TIMEOUT
                    value: "400"
                  - name: LIB
                    value: litmus
                  - name: AWS_SHARED_CREDENTIALS_FILE
                    value: /tmp/cloud_config.yml
                labels:
                  name: rds-instance-delete
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: latest
                secrets:
                  - name: cloud-secret
                    mountPath: /tmp/
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-rds-instance-delete-ztq.yaml
      - -saveName=/tmp/engine-name
      image: chaosnative/litmus-checker:2.12.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: rds-instance-delete-ztq
        path: /tmp/chaosengine-rds-instance-delete-ztq.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: rds-instance-delete-ztq
              labels:
                workflow_run_id: "{{workflow.uid}}"
                workflow_name: custom-1662133157
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: rds-instance-delete
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "10"
                        - name: CLUSTER_NAME
                          value: ""
                        - name: RDS_INSTANCE_IDENTIFIER
                          value: ""
                        - name: REGION
                          value: ""
                        - name: INSTANCE_AFFECTED_PERC
                          value: ""
                        - name: SEQUENCE
                          value: parallel
    metadata:
      labels:
        weight: "10"
    name: rds-instance-delete-ztq
    outputs: {}
  - container:
      args:
      - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: chaosnative/k8s:2.12.0
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
