apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
    subject: custom_litmus
    workflow_id: bd267dbc-c797-47ec-b51b-dbecf033633c
    workflows.argoproj.io/controller-instanceid: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
  name: custom-1662093060
  namespace: litmus
spec:
  concurrencyPolicy: Forbid
  schedule: 21 0-23 * * *
  startingDeadlineSeconds: 0
  timezone: Asia/Calcutta
  workflowMetadata:
    creationTimestamp: null
    labels:
      cluster_id: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
      workflow_id: bd267dbc-c797-47ec-b51b-dbecf033633c
      workflows.argoproj.io/controller-instanceid: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
  workflowSpec:
    arguments:
      parameters:
      - name: adminModeNamespace
        value: litmus
    entrypoint: custom-chaos
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: argo-chaos
    templates:
    - inputs: {}
      metadata: {}
      name: custom-chaos
      outputs: {}
      steps:
      - - arguments: {}
          name: install-chaos-experiments
          template: install-chaos-experiments
      - - arguments: {}
          name: pod-delete-ks1
          template: pod-delete-ks1
    - container:
        args:
        - kubectl apply -f /tmp/pod-delete-ks1.yaml -n {{workflow.parameters.adminModeNamespace}}
          &&  sleep 30
        command:
        - sh
        - -c
        image: chaosnative/k8s:2.12.0
        name: ""
        resources: {}
      inputs:
        artifacts:
        - name: pod-delete-ks1
          path: /tmp/pod-delete-ks1.yaml
          raw:
            data: |
              apiVersion: litmuschaos.io/v1alpha1
              description:
                message: |
                  Deletes a pod belonging to a deployment/statefulset/daemonset
              kind: ChaosExperiment
              metadata:
                name: pod-delete
                labels:
                  name: pod-delete
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: chaosexperiment
                  app.kubernetes.io/version: latest
              spec:
                definition:
                  scope: Namespaced
                  permissions:
                    - apiGroups:
                        - ""
                      resources:
                        - pods
                      verbs:
                        - create
                        - delete
                        - get
                        - list
                        - patch
                        - update
                        - deletecollection
                    - apiGroups:
                        - ""
                      resources:
                        - events
                      verbs:
                        - create
                        - get
                        - list
                        - patch
                        - update
                    - apiGroups:
                        - ""
                      resources:
                        - configmaps
                      verbs:
                        - get
                        - list
                    - apiGroups:
                        - ""
                      resources:
                        - pods/log
                      verbs:
                        - get
                        - list
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - pods/exec
                      verbs:
                        - get
                        - list
                        - create
                    - apiGroups:
                        - apps
                      resources:
                        - deployments
                        - statefulsets
                        - replicasets
                        - daemonsets
                      verbs:
                        - list
                        - get
                    - apiGroups:
                        - apps.openshift.io
                      resources:
                        - deploymentconfigs
                      verbs:
                        - list
                        - get
                    - apiGroups:
                        - ""
                      resources:
                        - replicationcontrollers
                      verbs:
                        - get
                        - list
                    - apiGroups:
                        - argoproj.io
                      resources:
                        - rollouts
                      verbs:
                        - list
                        - get
                    - apiGroups:
                        - batch
                      resources:
                        - jobs
                      verbs:
                        - create
                        - list
                        - get
                        - delete
                        - deletecollection
                    - apiGroups:
                        - litmuschaos.io
                      resources:
                        - chaosengines
                        - chaosexperiments
                        - chaosresults
                      verbs:
                        - create
                        - list
                        - get
                        - patch
                        - update
                        - delete
                  image: chaosnative/go-runner:ci
                  imagePullPolicy: Always
                  args:
                    - -c
                    - ./experiments -name pod-delete
                  command:
                    - /bin/bash
                  env:
                    - name: TOTAL_CHAOS_DURATION
                      value: "15"
                    - name: RAMP_TIME
                      value: ""
                    - name: FORCE
                      value: "true"
                    - name: CHAOS_INTERVAL
                      value: "5"
                    - name: PODS_AFFECTED_PERC
                      value: ""
                    - name: LIB
                      value: litmus
                    - name: TARGET_PODS
                      value: ""
                    - name: NODE_LABEL
                      value: ""
                    - name: SEQUENCE
                      value: parallel
                  labels:
                    name: pod-delete
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: experiment-job
                    app.kubernetes.io/version: latest
      metadata: {}
      name: install-chaos-experiments
      outputs: {}
    - container:
        args:
        - -file=/tmp/chaosengine-pod-delete-ks1.yaml
        - -saveName=/tmp/engine-name
        image: chaosnative/litmus-checker:2.12.0
        name: ""
        resources: {}
      inputs:
        artifacts:
        - name: pod-delete-ks1
          path: /tmp/chaosengine-pod-delete-ks1.yaml
          raw:
            data: |
              apiVersion: litmuschaos.io/v1alpha1
              kind: ChaosEngine
              metadata:
                namespace: "{{workflow.parameters.adminModeNamespace}}"
                generateName: pod-delete-ks1
                labels:
                  workflow_run_id: "{{workflow.uid}}"
                  workflow_name: custom-1662093060
              spec:
                appinfo:
                  appns: default
                  applabel: app=nginx
                  appkind: deployment
                engineState: active
                chaosServiceAccount: litmus-admin
                experiments:
                  - name: pod-delete
                    spec:
                      components:
                        env:
                          - name: TOTAL_CHAOS_DURATION
                            value: "30"
                          - name: CHAOS_INTERVAL
                            value: "10"
                          - name: FORCE
                            value: "false"
                          - name: PODS_AFFECTED_PERC
                            value: ""
      metadata:
        labels:
          weight: "10"
      name: pod-delete-ks1
      outputs: {}
status:
  active: null
  conditions: null
  lastScheduledTime: null
