apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
    subject: pod-auto-scaler_litmus
    workflow_id: 17c49815-bacc-457e-8819-b543576d137f
    workflows.argoproj.io/controller-instanceid: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
  name: nginx-pod-autoscaler-1662062984
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-autoscaler-hvx
        template: pod-autoscaler-hvx
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
  - container:
      args:
      - kubectl apply -f /tmp/pod-autoscaler-hvx.yaml -n {{workflow.parameters.adminModeNamespace}}
        |  sleep 30
      command:
      - sh
      - -c
      image: chaosnative/k8s:2.8.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-autoscaler-hvx
        path: /tmp/pod-autoscaler-hvx.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Scale the application replicas and test the node autoscaling on cluster
            kind: ChaosExperiment
            metadata:
              name: pod-autoscaler
              labels:
                name: pod-autoscaler
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: latest
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                    verbs:
                      - list
                      - get
                      - patch
                      - update
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: chaosnative/go-runner:ci
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name pod-autoscaler
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: RAMP_TIME
                    value: ""
                  - name: REPLICA_COUNT
                    value: "5"
                  - name: LIB
                    value: litmus
                labels:
                  name: pod-autoscaler
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: latest
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-pod-autoscaler-hvx.yaml
      - -saveName=/tmp/engine-name
      image: chaosnative/litmus-checker:2.8.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-autoscaler-hvx
        path: /tmp/chaosengine-pod-autoscaler-hvx.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: pod-autoscaler-hvx
              labels:
                instance_id: b43cc7bc-b061-4b5e-94ed-c38c812cb119
                workflow_name: pod-auto-scaler
            spec:
              engineState: active
              auxiliaryAppInfo: ""
              appinfo:
                appns: default
                applabel: app=nginx
                appkind: deployment
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-autoscaler
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: REPLICA_COUNT
                          value: "5"
                    probe: []
    metadata:
      labels:
        weight: "10"
    name: pod-autoscaler-hvx
    outputs: {}
  - container:
      args:
      - 'kubectl delete chaosengine -l ''instance_id in (b43cc7bc-b061-4b5e-94ed-c38c812cb119,
        )'' -n {{workflow.parameters.adminModeNamespace}} '
      command:
      - sh
      - -c
      image: chaosnative/k8s:2.8.0
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
