apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
    subject: vmware-process-kill-1662065605_litmus
    workflow_id: 763a7394-d5df-46e8-b14b-ea005c25a316
    workflows.argoproj.io/controller-instanceid: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
  name: vmware-process-kill-1662065605
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: vmware-vm-process-kill-g1q
        template: vmware-vm-process-kill-g1q
  - container:
      args:
      - kubectl apply -f /tmp/vmware-vm-process-kill-g1q.yaml -n {{workflow.parameters.adminModeNamespace}}
        &&  sleep 30
      command:
      - sh
      - -c
      image: chaosnative/k8s:2.12.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: vmware-vm-process-kill-g1q
        path: /tmp/vmware-vm-process-kill-g1q.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                It kills a process in a VMware instance for a certain chaos duration.
            kind: ChaosExperiment
            metadata:
              name: vmware-vm-process-kill
              labels:
                name: vmware-vm-process-kill
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: latest
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: chaosnative/go-runner:ci
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name vmware-process-kill
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "30"
                  - name: CHAOS_INTERVAL
                    value: "10"
                  - name: RAMP_TIME
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: GOVC_URL
                    valueFrom:
                      secretKeyRef:
                        name: vcenter-secret
                        key: VCENTERSERVER
                  - name: GOVC_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: vcenter-secret
                        key: VCENTERUSER
                  - name: GOVC_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: vcenter-secret
                        key: VCENTERPASS
                  - name: GOVC_INSECURE
                    value: "true"
                  - name: VM_NAME
                    value: ""
                  - name: VM_USER_NAME
                    value: ""
                  - name: VM_PASSWORD
                    value: ""
                  - name: PROCESS_IDS
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                labels:
                  name: vmware-vm-process-kill
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: latest
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-vmware-vm-process-kill-g1q.yaml
      - -saveName=/tmp/engine-name
      image: chaosnative/litmus-checker:2.12.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: vmware-vm-process-kill-g1q
        path: /tmp/chaosengine-vmware-vm-process-kill-g1q.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: vmware-vm-process-kill-g1q
              labels:
                workflow_run_id: "{{workflow.uid}}"
                workflow_name: vmware-process-kill-1662065605
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: vmware-vm-process-kill
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "10"
                        - name: VM_NAME
                          value: vm2
                        - name: VM_USER_NAME
                          value: vm2
                        - name: VM_PASSWORD
                          value: "123"
                        - name: PROCESS_IDS
                          value: 10084,10097
                        - name: SEQUENCE
                          value: parallel
                    probe: []
    metadata:
      labels:
        weight: "10"
    name: vmware-vm-process-kill-g1q
    outputs: {}
status:
  finishedAt: null
  startedAt: null
