apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
    subject: vmware-disk-loss_litmus
    workflow_id: c15205e5-d2da-44ce-aebb-24fb8f153170
    workflows.argoproj.io/controller-instanceid: 5fa54a9d-063e-468b-9a80-a7ebca16ea82
  name: vmware-disk-loss-1662066608
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: vmware-io-stress-krb
        template: vmware-io-stress-krb
  - container:
      args:
      - kubectl apply -f /tmp/vmware-disk-loss-urb.yaml -n {{workflow.parameters.adminModeNamespace}}
        && kubectl apply -f /tmp/vmware-io-stress-krb.yaml -n {{workflow.parameters.adminModeNamespace}}
        &&  sleep 30
      command:
      - sh
      - -c
      image: chaosnative/k8s:2.12.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: vmware-disk-loss-urb
        path: /tmp/vmware-disk-loss-urb.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: >
                VMWare Disk Loss experiment causes the detachment of Virtual Disks attached
                to a VM for a specified duration of time and later attaches them back to the
                VM.
            kind: ChaosExperiment
            metadata:
              name: vmware-disk-loss
              labels:
                name: vmware-disk-loss
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: latest
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: chaosnative/go-runner:ci
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name vmware-disk-loss
                command:
                  - /bin/bash
                env:
                  - name: VCENTERSERVER
                    valueFrom:
                      secretKeyRef:
                        name: vcenter-secret
                        key: VCENTERSERVER
                  - name: VCENTERUSER
                    valueFrom:
                      secretKeyRef:
                        name: vcenter-secret
                        key: VCENTERUSER
                  - name: VCENTERPASS
                    valueFrom:
                      secretKeyRef:
                        name: vcenter-secret
                        key: VCENTERPASS
                  - name: TOTAL_CHAOS_DURATION
                    value: "30"
                  - name: CHAOS_INTERVAL
                    value: "30"
                  - name: LIB
                    value: litmus
                  - name: RAMP_TIME
                    value: ""
                  - name: VIRTUAL_DISK_IDS
                    value: ""
                  - name: APP_VM_MOIDS
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                labels:
                  name: vmware-disk-loss
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: latest
      - name: vmware-io-stress-krb
        path: /tmp/vmware-io-stress-krb.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: >
                It inject IO stress chaos on the provided VMware VMs for a certain chaos
                duration.
            kind: ChaosExperiment
            metadata:
              name: vmware-io-stress
              labels:
                name: vmware-io-stress
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: latest
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: chaosnative/go-runner:ci
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name vmware-io-stress
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "30"
                  - name: CHAOS_INTERVAL
                    value: "10"
                  - name: RAMP_TIME
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: GOVC_URL
                    valueFrom:
                      secretKeyRef:
                        name: vcenter-secret
                        key: VCENTERSERVER
                  - name: GOVC_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: vcenter-secret
                        key: VCENTERUSER
                  - name: GOVC_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: vcenter-secret
                        key: VCENTERPASS
                  - name: GOVC_INSECURE
                    value: "true"
                  - name: SEQUENCE
                    value: parallel
                labels:
                  name: vmware-io-stress
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: latest
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-vmware-io-stress-krb.yaml
      - -saveName=/tmp/engine-name
      image: chaosnative/litmus-checker:2.12.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: vmware-io-stress-krb
        path: /tmp/chaosengine-vmware-io-stress-krb.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: vmware-io-stress-krb
              labels:
                workflow_run_id: "{{workflow.uid}}"
                workflow_name: vmware-disk-loss-1662066608
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: vmware-io-stress
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "30"
                        - name: VM_NAME
                          value: vm2
                        - name: VM_USER_NAME
                          value: vm2
                        - name: VM_PASSWORD
                          value: "123"
                        - name: FILESYSTEM_UTILIZATION_PERCENTAGE
                          value: "80"
                        - name: FILESYSTEM_UTILIZATION_BYTES
                          value: ""
                        - name: NUMBER_OF_WORKERS
                          value: "4"
                        - name: VOLUME_MOUNT_PATH
                          value: /tmp
                        - name: CPU_CORES
                          value: "4"
                        - name: SEQUENCE
                          value: parallel
                    probe: []
    metadata:
      labels:
        weight: "10"
    name: vmware-io-stress-krb
    outputs: {}
status:
  finishedAt: null
  startedAt: null
