apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: node-memory-hog
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: Harness
spec:
  displayName: node-memory-hog
  categoryDescription: |
    Kubernetes Node memory hog fault disrupts the state of Kubernetes resources. This fault injects a memory spike on a node where the application pod is scheduled.
    - Memory hog on a particular node where the application deployment is available.
    - After the test, the recovery should be manual for the application pod and node in case they are not in an appropriate state. 
  keywords:
    - Kubernetes

  platforms:
    - GKE
    - EKS
    - AKS
    - Kind
    - Rancher
    - OpenShift(OKD)
  experiments:
    - k8s-node-memory-hog
  chaosType: infra
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url: ""
      mediatype: ""
