apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    subject: custom_litmus
  name: test-push-form-create
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: ecs-container-io-stress-kzr
        template: ecs-container-io-stress-kzr
    - - arguments: {}
        name: ec2-stop-by-id-ne5
        template: ec2-stop-by-id-ne5
  - container:
      args:
      - kubectl apply -f /tmp/ecs-container-io-stress-kzr.yaml -n {{workflow.parameters.adminModeNamespace}}
        | kubectl apply -f /tmp/ec2-stop-by-id-ne5.yaml -n {{workflow.parameters.adminModeNamespace}}
        |  sleep 30
      command:
      - sh
      - -c
      image: chaosnative/k8s:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: ecs-container-io-stress-kzr
        path: /tmp/ecs-container-io-stress-kzr.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: >
                Inject io stress on the aws ecs task containers for a specific chaos duration
            kind: ChaosExperiment
            metadata:
              name: ecs-container-io-stress
              labels:
                name: ecs-container-io-stress
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: latest
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: chaosnative/go-runner:ci
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name ecs-container-io-stress
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "30"
                  - name: RAMP_TIME
                    value: ""
                  - name: CHAOS_INTERVAL
                    value: "10"
                  - name: LIB
                    value: litmus
                  - name: DOCUMENT_PATH
                    value: Litmus-AWS-SSM-Docs-For-IO-Stress.yml
                  - name: DOCUMENT_NAME
                    value: Litmus-AWS-SSM-Docs-For-IO-Stress
                  - name: DOCUMENT_FORMAT
                    value: YAML
                  - name: DOCUMENT_TYPE
                    value: Command
                  - name: AWS_SHARED_CREDENTIALS_FILE
                    value: /tmp/cloud_config.yml
                labels:
                  name: ecs-container-io-stress
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: latest
                secrets:
                  - name: cloud-secret
                    mountPath: /tmp/
      - name: ec2-stop-by-id-ne5
        path: /tmp/ec2-stop-by-id-ne5.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Stopping an EC2 instance identified by ID.
            kind: ChaosExperiment
            metadata:
              name: ec2-stop-by-id
              labels:
                name: ec2-stop-by-id
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: latest
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - secrets
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                  - apiGroups:
                      - ""
                    resources:
                      - nodes
                    verbs:
                      - get
                      - list
                image: chaosnative/go-runner:ci
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name ec2-stop-by-id
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "30"
                  - name: CHAOS_INTERVAL
                    value: "30"
                  - name: RAMP_TIME
                    value: ""
                  - name: MANAGED_NODEGROUP
                    value: disable
                  - name: EC2_INSTANCE_ID
                    value: ""
                  - name: REGION
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                  - name: AWS_SHARED_CREDENTIALS_FILE
                    value: /tmp/cloud_config.yml
                  - name: LIB
                    value: litmus
                labels:
                  name: ec2-stop-by-id
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: latest
                secrets:
                  - name: cloud-secret
                    mountPath: /tmp/
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-ecs-container-io-stress-kzr.yaml
      - -saveName=/tmp/engine-name
      image: chaosnative/litmus-checker:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: ecs-container-io-stress-kzr
        path: /tmp/chaosengine-ecs-container-io-stress-kzr.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: ecs-container-io-stress-kzr
              labels:
                instance_id: 48a52ae2-68c5-41d9-88d8-7d204d6ed165
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: ecs-container-io-stress
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "10"
                        - name: CLUSTER_NAME
                          value: ""
                        - name: SERVICE_NAME
                          value: ""
                        - name: REGION
                          value: ""
                        - name: FILESYSTEM_UTILIZATION_BYTES
                          value: "1"
                        - name: VOLUME_MOUNT_PATH
                          value: /tmp
                        - name: NUMBER_OF_WORKERS
                          value: "1"
                        - name: INSTALL_DEPENDENCIES
                          value: "True"
                        - name: SEQUENCE
                          value: parallel
    metadata: {}
    name: ecs-container-io-stress-kzr
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-ec2-stop-by-id-ne5.yaml
      - -saveName=/tmp/engine-name
      image: chaosnative/litmus-checker:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: ec2-stop-by-id-ne5
        path: /tmp/chaosengine-ec2-stop-by-id-ne5.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: ec2-stop-by-id-ne5
              labels:
                instance_id: aaca15cb-390d-44ac-85af-a5d3b58b46d6
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: ec2-stop-by-id
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "30"
                        - name: EC2_INSTANCE_ID
                          value: ""
                        - name: REGION
                          value: ""
                        - name: MANAGED_NODEGROUP
                          value: disable
    metadata: {}
    name: ec2-stop-by-id-ne5
    outputs: {}
status:
  finishedAt: null
  startedAt: null
