apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: kubelet-service-kill
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: Harness
spec:
  displayName: kubelet-service-kill
  categoryDescription: |
    kubelet-service-kill contains killing kubelet service gracefully for a certain chaos duration.
    - Causes replicas may be evicted or becomes unreachable on account on nodes turning unschedulable (Not Ready) due to kubelet service kill.
    - The application node should be healthy once chaos is stopped and the services are reaccessable. 
    
  keywords:
    - Kubernetes
  platforms:
    - GKE
    - Packet(Kubeadm)
    - Minikube
    - EKS
    - AKS
  scenarios:
    - k8s-kubelet-service-kill
  maintainers:
    - name: Udit Gaurav
      email: udit.gaurav@harness.io
  minKubeVersion: 1.12.0
  provider:
    name: Harness
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - base64data: ""
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/wings-software/enterprise-chaos-hub/main/experiments/kubernetes/kubelet-service-kill/experiment.yaml 
