apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: kubelet-service-kill
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: Harness
spec:
  displayName: kubelet-service-kill
  categoryDescription: |
    kubelet-service-kill fault kills the kubelet service gracefully for a certain chaos duration.
    - Replicas may be evicted or become unreachable on account on nodes turning unschedulable (Not Ready) due to kubelet service kill.
    - The application node should be healthy once chaos is stopped and the services are reaccessable. 
    
  keywords:
    - Kubernetes
  platforms:
    - GKE
    - Packet(Kubeadm)
    - Minikube
    - EKS
    - AKS
  experiments:
    - k8s-kubelet-service-kill
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - base64data: ""
      mediatype: ""
