apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
spec:
  appinfo:
    appns: "default"
    applabel: "app=nginx"
    appkind: "deployment"
  # It can be active/stop
  engineState: "active"
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ""
  chaosServiceAccount: pod-dns-spoof-sa
  experiments:
    - name: pod-dns-spoof
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60" # in seconds

            # map of the target hostnames eg. '{"abc.com":"spoofabc.com"}' . If empty no queries will be spoofed
            - name: SPOOF_MAP
              value: '{"google.com":"fakegoogle.com"}'

            # provide the name of container runtime, it supports docker, containerd, crio
            - name: CONTAINER_RUNTIME
              value: "docker"

            # provide the socket file path
            - name: SOCKET_PATH
              value: "/var/run/docker.sock"

             ## percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ""
          probe:
            - name: healthcheck
              type: cmdProbe
              mode: Edge
              runProperties:
                probeTimeout: 180
                retry: 0
                interval: 1
                stopOnFailure: true
              cmdProbe/inputs:
                command: ./healthcheck -name pod-level
                source:
                  image: chaosnative/go-runner:ci
                  inheritInputs: true
                comparator:
                  type: string
                  criteria: contains
                  value: "[P000]"

