apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: pod-dns-spoof
  version: 0.1.0
  annotations:
    categories: kubernetes
spec:
  displayName: pod-dns-spoof
  categoryDescription: >
    Pod DNS Spoof fault spoofs particular DNS requests in a target pod container to desired target hostnames.
  keywords:
    - Kubernetes
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - base64data: ""
      mediatype: ""
