apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: pod-cpu-hog-exec
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: Harness
spec:
  displayName: pod-cpu-hog-exec
  categoryDescription: |
    pod-cpu-hog-exec fault consumes CPU resouces of specified containers in Kubernetes pods.
    - Causes high CPU resource consumption utilizing one or more cores by triggering md5sum commands.
    - The application pod should be healthy once chaos is stopped. Expectation is that service-requests should be served despite chaos.
  keywords:
    - Kubernetes

  platforms:
    - GKE
    - Packet(Kubeadm)
    - Minikube
    - EKS
    - AKS
    - Kind
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - base64data: ""
      mediatype: ""
