apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: pod-http-modify-header
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: CNCF
spec:
  displayName: pod-http-modify-header
  categoryDescription: |
    Pod-http-modify-header contains chaos to disrupt http requests of kubernetes pods. This experiment can modify headers of incoming requests or the response from the service targetted. 
    - Causes modification of request/response headers of the HTTP request.
    - The application pod should be healthy once chaos is stopped. Service-requests should be served despite chaos.
  keywords:
    - Kubernetes
  platforms:
    - GKE
    - Minikube 
    - EKS
  maintainers:
    - name: Akash Shrivastava
      email: akash.shrivastava@harness.io
  minKubeVersion: 1.12.0
  provider:
    name: Harness
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  icon:
    - base64data: ""
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/pod-http-modify-header/experiment.yaml
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
