apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: pod-http-modify-header
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: CNCF
spec:
  displayName: pod-http-modify-header
  categoryDescription: |
    Pod-http-modify-header fault disrupts http requests of kubernetes pods. This fault can modify headers of incoming requests or the response from the service targetted. 
    - Causes modification of request/response headers of the HTTP request.
    - The application pod should be healthy once chaos is stopped. Service-requests should be served despite chaos.
  keywords:
    - Kubernetes
  platforms:
    - GKE
    - Minikube 
    - EKS
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  icon:
    - base64data: ""
      mediatype: ""
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
