apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2022-07-27T10:28:08Z
  name: aws-ssm-chaos-by-tag
  version: 0.1.0
  annotations:
    categories: AWS
    vendor: Harness
spec:
  displayName: aws-ssm-chaos-by-tag
  categoryDescription: |
    AWS SSM Chaos By Tag contains chaos to disrupt the state of infra resources. The experiment can induce chaos on AWS resources using Amazon SSM Run Command This is carried out by using SSM Docs that defines the actions performed by Systems Manager on your managed instances (having SSM agent installed) which let us perform chaos experiments on resources. 
    - Causes chaos on AWS ec2 instances with given instance tag using SSM docs for total chaos duration with the specified chaos interval.
    - Tests deployment sanity (replica availability & uninterrupted service) and recovery workflows of the target application pod(if provided).
  keywords:
    - AWS
  platforms:
    - AWS
  scenarios:
    - aws-ssm-chaos-by-tag
  chaosType: infra
  maintainers:
    - name: Udit Gaurav
      email: udit.gaurav@harness.io
  provider:
    name: Harness
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/aws-ssm/aws-ssm-chaos-by-tag/experiment.yaml
