apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: node-network-loss
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: Harness
spec:
  displayName: node-network-loss
  categoryDescription: >
    Node network loss fault injects network packet loss for the provided nodes through a certain chaos duration.
  keywords:
    - Kubernetes

  platforms:
    - GKE
    - AWS(KOPS)
    - Packet(Kubeadm)
    - Konvoy
    - EKS
    - AKS
  experiments:
    - k8s-node-network-loss
  chaosType: infra
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url: ""
      mediatype: ""
