apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: node-io-stress
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: Harness
spec:
  displayName: node-io-stress
  categoryDescription: |
    This fault causes disk stress on the Kubernetes node. This fault aims to verify the resiliency of applications that share this disk resource for ephemeral or persistent storage purposes..
    - Disk stress on a particular node filesystem where the application deployment is available.
    - The amount of disk stress can be either specifed as the size in percentage of the total free space on the file system or simply in Gigabytes(GB)
  keywords:
    - Kubernetes

  platforms:
    - GKE
    - EKS
    - AKS
  experiments:
    - k8s-node-io-stress
  chaosType: infra
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url: ""
      mediatype: ""
