apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: pod-autoscaler
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: Harness
spec:
  displayName: pod-autoscaler
  categoryDescription: |
    This fault aims to check the ability of nodes to accommodate the number of replicas a given application pod.
    It can be used for other cases as well, such as for checking the Node auto-scaling feature. For example, check if the pods are successfully rescheduled within a specified period in cases where the existing nodes are already running at the specified limits.
  keywords:
    - Kubernetes

  platforms:
    - GKE
    - EKS
    - Minikube
    - AKS
  chaosType: infra
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon: 
    - url: 
      mediatype: ""
