apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: pod-network-latency
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: Harness
spec:
  displayName: pod-network-latency
  categoryDescription: |
    Pod-network-latency contains chaos to disrupt network connectivity of kubernetes pods. Experiments can inject random network delays on the app replica pods. 
    - Causes flaky access to application replica by injecting network delay using pumba.
    - The application pod should be healthy once chaos is stopped. Service-requests should be served despite chaos.
  keywords:
    - Kubernetes

  platforms:
    - GKE
    - Minikube 
    - Packet(Kubeadm)
    - EKS
    - AKS
  maintainers:
    - name: ksatchit
      email: karthik.s@harness.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - base64data: ""
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/pod-network-latency/experiment.yaml