apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: pod-dns-error
  version: 0.1.0
  annotations:
    categories: kubernetes
spec:
  displayName: pod-dns-error
  categoryDescription: >
    Pod DNS Error injects dns failure/error in target pod containers
  keywords:
    - Kubernetes
  minKubeVersion: 1.12.0
  provider:
    name: Harness
  maintainers:
    - name: ksatchit
      email: karthik.s@harness.io
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - base64data: ""
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/pod-dns-error/experiment.yaml
