apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-network-chaos
  namespace: default
spec:
  # It can be active/stop
  engineState: 'active'
  appinfo:
    appns: 'default'
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: 'app=nginx'
    appkind: 'deployment'
  chaosServiceAccount: pod-network-partition-sa
  experiments:
    - name: pod-network-partition
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '60' # in seconds
          probe:
            - name: healthcheck
              type: cmdProbe
              mode: Edge
              runProperties:
                probeTimeout: 180
                retry: 0
                interval: 1
                stopOnFailure: true
              cmdProbe/inputs:
                command: ./healthcheck -name pod-level
                source:
                  image: chaosnative/go-runner:ci
                  inheritInputs: true
                comparator:
                  type: string
                  criteria: contains
                  value: "[P000]"

