apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: node-chaos
  namespace: default
spec:
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx 
  auxiliaryAppInfo: ''
  chaosServiceAccount: litmus-admin
  experiments:
    - name: node-network-latency
      spec:
        components:
        # nodeSelector: 
        #   # provide the node labels
        #   kubernetes.io/hostname: 'node02'        
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '60'
              
            - name: CONTAINER_RUNTIME
              value: 'docker'

            - name: NETWORK_LATENCY
              value: '2000'

            - name: SOCKET_PATH
              value: /var/run/docker.sock

            - name: DESTINATION_IPS
              value: ''

            - name: TARGET_NODE
              value: ''

            - name: DESTINATION_HOSTS
              value: ''
        probe:
          - name: healthcheck
            type: cmdProbe
            mode: Edge
            runProperties:
              probeTimeout: 180
              retry: 0
              interval: 1
              stopOnFailure: true
            cmdProbe/inputs:
              command: ./healthcheck -name node-level
              source:
                image: chaosnative/go-runner:ci
                inheritInputs: true
              comparator:
                type: string
                criteria: contains
                value: "[P000]"