---
apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Injects network packet latency on the provided nodes for a certain chaos duration.
kind: ChaosExperiment

metadata:
  name: node-network-latency
  labels:
    name: node-network-latency
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: ci
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - deletecollection
      - apiGroups:
          - ""
        resources:
          - events
        verbs:
          - create
          - get
          - list
          - patch
          - update
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
      - apiGroups:
          - ""
        resources:
          - pods/log
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - ""
        resources:
          - pods/exec
        verbs:
          - get
          - list
          - create
      - apiGroups:
          - apps
        resources:
          - deployments
          - statefulsets
          - replicasets
          - daemonsets
        verbs:
          - list
          - get
      - apiGroups:
          - apps.openshift.io
        resources:
          - deploymentconfigs
        verbs:
          - list
          - get
      - apiGroups:
          - ""
        resources:
          - replicationcontrollers
        verbs:
          - get
          - list
      - apiGroups:
          - argoproj.io
        resources:
          - rollouts
        verbs:
          - list
          - get
      - apiGroups:
          - batch
        resources:
          - jobs
        verbs:
          - create
          - list
          - get
          - delete
          - deletecollection
      - apiGroups:
          - litmuschaos.io
        resources:
          - chaosengines
          - chaosexperiments
          - chaosresults
        verbs:
          - create
          - list
          - get
          - patch
          - update
          - delete
    image: chaosnative/go-runner:ci
    imagePullPolicy: Always
    args:
      - -c
      - ./experiments -name node-network-latency
    command:
      - /bin/bash
    env:
      - name: TARGET_CONTAINER
        value: ""
      - name: LIB_IMAGE
        value: chaosnative/go-runner:ci
      - name: NETWORK_INTERFACE
        value: eth0
      - name: NETWORK_LATENCY
        value: "2000"
      - name: TOTAL_CHAOS_DURATION
        value: "60"
      - name: RAMP_TIME
        value: ""
      - name: LIB
        value: litmus
      - name: TARGET_NODE
        value: ""
      - name: CONTAINER_RUNTIME
        value: docker
      - name: DESTINATION_IPS
        value: ""
      - name: DESTINATION_HOSTS
        value: ""
      - name: DEFAULT_HEALTH_CHECK
        value: 'false'
      - name: SOCKET_PATH
        value: /var/run/docker.sock
      - name: SEQUENCE
        value: parallel
    labels:
      name: node-network-latency
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/runtime-api-usage: "true"
      app.kubernetes.io/version: ci
