apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-http-chaos
  namespace: default
spec:
  # It can be active/stop
  engineState: 'active'
  appinfo:
    appns: 'default'
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: 'app=nginx'
    appkind: 'deployment'
  chaosServiceAccount: pod-http-latency-sa
  experiments:
    - name: pod-http-latency
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '60' # in seconds

            - name: LATENCY
              value: '2000' #in ms

            # port of the target service
            - name: TARGET_SERVICE_PORT
              value: "80"

            # provide the name of container runtime
            # it supports docker, containerd, crio
            - name: CONTAINER_RUNTIME
              value: 'docker'

            # provide the socket file path
            - name: SOCKET_PATH
              value: '/var/run/docker.sock'

             ## percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ''
          probe:
            - name: healthcheck
              type: cmdProbe
              mode: Edge
              runProperties:
                probeTimeout: 180
                retry: 0
                interval: 1
                stopOnFailure: true
              cmdProbe/inputs:
                command: ./healthcheck -name pod-level
                source:
                  image: chaosnative/go-runner:ci
                  inheritInputs: true
                comparator:
                  type: string
                  criteria: contains
                  value: "[P000]"
