apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: pod-http-latency
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: Harness
spec:
  displayName: pod-http-latency
  categoryDescription: |
    Pod-http-latency fault disrupts http requests of kubernetes pods. This fault can inject random http response delays on the app replica pods. 
    - Causes flaky access to application replica by injecting http response delay using toxiproxy.
    - The application pod should be healthy once chaos is stopped. Service-requests should be served despite chaos.
  keywords:
    - Kubernetes
  platforms:
    - GKE
    - Minikube 
    - EKS
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - base64data: ""
      mediatype: ""
