apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    subject: custom_litmus
  name: dadad
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: aws-ssm-chaos-by-tag-bs8
        template: aws-ssm-chaos-by-tag-bs8
  - container:
      args:
      - kubectl apply -f /tmp/aws-ssm-chaos-by-tag-bs8.yaml -n {{workflow.parameters.adminModeNamespace}}
        |  sleep 30
      command:
      - sh
      - -c
      image: chaosnative/k8s:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: aws-ssm-chaos-by-tag-bs8
        path: /tmp/aws-ssm-chaos-by-tag-bs8.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Execute AWS SSM Chaos on given ec2 instance Tag
            kind: ChaosExperiment
            metadata:
              name: aws-ssm-chaos-by-tag
              labels:
                name: aws-ssm-chaos-by-tag
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: latest
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - secrets
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: chaosnative/go-runner:ci
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name aws-ssm-chaos-by-tag
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: CHAOS_INTERVAL
                    value: "60"
                  - name: RAMP_TIME
                    value: ""
                  - name: EC2_INSTANCE_TAG
                    value: ""
                  - name: REGION
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                  - name: AWS_SHARED_CREDENTIALS_FILE
                    value: /tmp/cloud_config.yml
                  - name: INSTANCE_AFFECTED_PERC
                    value: ""
                  - name: DOCUMENT_NAME
                    value: ""
                  - name: DOCUMENT_TYPE
                    value: ""
                  - name: DOCUMENT_FORMAT
                    value: ""
                  - name: DOCUMENT_PATH
                    value: ""
                  - name: INSTALL_DEPENDENCIES
                    value: "True"
                  - name: NUMBER_OF_WORKERS
                    value: "1"
                  - name: MEMORY_PERCENTAGE
                    value: "80"
                  - name: CPU_CORE
                    value: "0"
                  - name: LIB
                    value: litmus
                labels:
                  name: aws-ssm-chaos-by-tag
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: latest
                secrets:
                  - name: cloud-secret
                    mountPath: /tmp/
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-aws-ssm-chaos-by-tag-bs8.yaml
      - -saveName=/tmp/engine-name
      image: chaosnative/litmus-checker:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: aws-ssm-chaos-by-tag-bs8
        path: /tmp/chaosengine-aws-ssm-chaos-by-tag-bs8.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: aws-ssm-chaos-by-tag-bs8
              labels:
                instance_id: cfb2864b-b507-4e20-a987-b89b5a60649d
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: aws-ssm-chaos-by-tag
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: CHAOS_INTERVAL
                          value: "60"
                        - name: EC2_INSTANCE_TAG
                          value: ""
                        - name: REGION
                          value: ""
                        - name: MEMORY_PERCENTAGE
                          value: "80"
                        - name: CPU_CORE
                          value: "0"
                        - name: DOCUMENT_NAME
                          value: ""
                        - name: DOCUMENT_TYPE
                          value: ""
                        - name: DOCUMENT_FORMAT
                          value: ""
                        - name: DOCUMENT_PATH
                          value: ""
                        - name: INSTALL_DEPENDENCIES
                          value: "True"
    metadata: {}
    name: aws-ssm-chaos-by-tag-bs8
    outputs: {}
status:
  finishedAt: null
  startedAt: null
