apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: aws
  version: 0.1.0
  annotations:
    categories: AWS
    chartDescription: Injects faults on aws services
spec:
  displayName: AWS Chaos
  categoryDescription: >
    AWS chaos contains different chaos experiments for AWS cloud provider to test the app/platform service availability. It uses AWS command to carry the fault logic in the instance. It will install all the experiments which can be used to inject chaos into the aws services like ec2,ecs,s3 and so on.
  experiments:
    - name: ecs-instance-stop
      description: It injects ecs-instance-stop chaos on ecs cluster
    - name: elb-az-down
      description: It injects AZ down chaos on ELB for a certain chaos duration.
    - name: ecs-container-network-loss
      description: It injects ecs-container-network-loss chaos on a aws ecs cluster
    - name: ecs-container-network-latency
      description: It injects ecs-container-network-latency chaos on a aws ecs cluster
    - name: ecs-container-cpu-hog
      description: It injects ecs-container-cpu-hog chaos on the task container of ecs cluster.
    - name: ecs-container-io-stress
      description: It injects ecs-container-io-stress chaos on the task container of ecs cluster.
    - name: ecs-container-memory-hog
      description: It injects ecs-container-memory-hog chaos on the task container of ecs cluster.
    - name: ec2-cpu-hog
      description: It injects CPU stress chaos on AWS EC2 instance.
    - name: ec2-io-stress
      description: It injects IO stress chaos on the AWS EC2 instance.
    - name: ec2-memory-hog
      description: It injects Memory stress chaos on the aws ec2 instance.
    - name: ec2-network-loss
      description: It injects Network loss chaos on the aws ec2 instance.
    - name: ec2-network-latency
      description: It injects Network latency chaos on the aws ec2 instance.
    - name: ecs-agent-stop
      description: It stops all the ECS agent container running on the container instances of ecs cluster 
    - name: aws-ssm-chaos-by-id
      description: It allow to perform in-vm chaos experiment using aws ssm service and ec2 instance id.
    - name: aws-ssm-chaos-by-tag
      description: It allow to perform in-vm chaos experiment using aws ssm service and ec2 instance tag.
    - name: ec2-stop-by-id
      description: It stops the AWS EC2 instance identified by ID for a certain chaos duration. 
    - name: ec2-stop-by-tag
      description: It stops the AWS EC2 instance identified by Tag for a certain chaos duration. 
    - name: ec2-http-latency
      description: It injects ec2-http-latency chaos on AWS EC2 instance.
    - name: ec2-http-modify-header
      description: It injects ec2-http-modify-header chaos on AWS EC2 instance.
    - name: ec2-http-modify-body
      description: It injects ec2-http-modify-body chaos on AWS EC2 instance.
    - name: ec2-http-status-code
      description: It injects ec2-http-status-code chaos on AWS EC2 instance.
    - name: ec2-http-reset-peer
      description: It injects ec2-http-reset-peer chaos on AWS EC2 instance.
    - name: ebs-loss-by-id
      description: It detach the EBS volume from AWS EC2 instance identified by ID for a certain chaos duration. 
    - name: ebs-loss-by-tag
      description: It detach the EBS volume from AWS EC2 instance identified by Tag for a certain chaos duration. 
    - name: rds-instance-delete
      description: It injects the rds-instance-delete chaos on the rds instances/cluster. 
    - name: rds-instance-reboot
      description: It injects the rds-instance-reboot chaos on the rds instances/cluster. 
    - name: ec2-dns-chaos
      description: It injects the dns chaos on the EC2 instance for a certain chaos duration.
    - name: ec2-process-kill
      description: It injects the process-kill chaos on the EC2 instance for a certain chaos duration.

  keywords:
    - AWS
  maintainers:
    - name: Udit Gaurav
      email: udit.gaurav@harness.io
    - name: Vedant Shrotria
      email: vedant.shrotria@harness.io
  minKubeVersion: 1.12.0
  provider:
    name: Harness
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
    - name: Kubernetes Slack
      url: https://slack.kubernetes.io/
    - name: Documentation
      url: ''
  icon:
    - url: https://raw.githubusercontent.com/litmuschaos/charthub.litmuschaos.io/master/public/litmus.ico
      mediatype: image/png
  chaosexpcrdlink: https://raw.githubusercontent.com/chaosnative/chaos-charts/master/charts/aws/experiments.yaml
