apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2022-07-28T10:28:08Z
  name: ebs-loss-by-tag
  version: 0.1.0
  annotations:
    categories: AWS
    vendor: Harness
spec:
  displayName: ebs-loss-by-tag
  categoryDescription: |
    EBS Loss By Tag contains chaos to disrupt state of infra resources. The experiment can induce ebs volume loss against specified application for given volume tag. 
    - Causes ebs volume loss by tag from node or ec2 instance for certain chaos interval from total chaos duration.
    - Tests deployment sanity (replica availability & uninterrupted service) and recovery workflows of the application pod
  keywords:
    - AWS 
  platforms:
    - AWS
  scenarios:
    - aws-ebs-loss-by-tag
  chaosType: infra
  maintainers:
    - name: Udit Gaurav
      email: udit.gaurav@harness.io
  provider:
    name: Harness
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/kube-aws/ebs-loss-by-tag/experiment.yaml
